-- 테스트 유저 생성 INSERT 문 (ID=1)

-- ID를 1로 강제 설정하기 위해 IDENTITY 제약 해제
ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 테스트 유저 삽입
INSERT INTO users (id, username, email, password_hash, total_points, created_at) 
VALUES (1, 'testuser', 'test@sleepcash.com', 'test_password_hash', 1000, CURRENT_TIMESTAMP);

-- IDENTITY 제약 다시 활성화
ALTER TABLE users ALTER COLUMN id SET GENERATED ALWAYS AS IDENTITY;
